security:
    role_hierarchy:
        ROLE_VISITOR: ROLE_USER
        ROLE_ADMIN: ROLE_VISITOR

    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_secured_area:
            pattern: ^/admin
            anonymous: ~
            provider: app_user_provider
            form_login:
                login_path: admin_login
                check_path: admin_login_check
                username_parameter: username
                password_parameter: password
            logout:
                path: admin_logout
                target: admin_login
            guard:
                authenticators:
                    - App\Security\AdminAuthenticator

        main:
            pattern: ^/
            anonymous: true
            lazy: true

    access_control:
        - { path: '^/admin/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: '^/admin/(country|genre|channel|warning)/create', roles: ROLE_ADMIN, method: 'POST' }
        - { path: '^/admin/(country|genre|channel|warning)/update', roles: ROLE_ADMIN, method: 'POST' }
        - { path: '^/admin/(country|genre|channel|warning)/delete', roles: ROLE_ADMIN, method: 'DELETE' }
        - { path: '^/admin/(main|country|genre|channel|warning)', roles: ROLE_VISITOR }

        - { path: '^/admin', roles: ROLE_ADMIN }
