vich_uploader:
    db_driver: orm

    mappings:
        default:
            uri_prefix: '/uploads'
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            directory_namer: App\VichUploader\DirectoryNamer