monolog:
    channels: ['app_debug']
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        app_debug:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%_app_debug.log'
            level: debug
            max_files: 10
            channels: [ 'app_debug' ]